### ISSUE TITLE
The plugin blocks all expressions in Bitwig

### ISSUE THREAD

**Issue by TjShredder** [gbevin/ShowMIDI#24]
The title says all. If I place it in front of a MPE capable instrument to monitor incoming Midi, the expressions are blocked. The LinnStrument pitch bend isn't passed on anymore...
And if you are at it, just list expressions as well. Would be very helpful for trouble shooting...

**Comment by gbevin** [comment]
Which plugin format are you using?

**Comment by TjShredder** [comment]
It happens with CLAP, VST3 and VST2. The only two messages I see, is the note on/off and pp, which I assume means poly pressure. Nothing else appears. Maybe it would be fine if there is also an instrument version of the plugin. As FX I can't force Bitwig to send Midi instead of expressions...

**Comment by gbevin** [comment]
This seems to be a problem with Bitwig, when I try VST3 in Reaper, everything is passed correctly. There seems to be a problem with the CLAP plugin format, that I'll report back to the creator because that seems to be passing CCs but not channel pressure.

I encourage you to contact Bitwig and ask them to look into this.
